# Generated by Django 4.1.5 on 2023-01-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
