# Generated by Django 4.1.5 on 2023-01-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_conversationmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='content',
        ),
    ]
