# Generated by Django 4.1.5 on 2023-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_conversationmessage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
