# Generated by Django 4.1.4 on 2023-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_skillset_required_alter_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(max_length=104, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
