# Generated by Django 4.1.5 on 2023-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_application_date_of_birth_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
