# Generated by Django 4.1.5 on 2023-01-10 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary1',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
