# Generated by Django 4.1.5 on 2023-01-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_salary1_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary1',
        ),
    ]
