# Generated by Django 4.1.5 on 2023-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_job_salary1'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
