# Generated by Django 4.1.5 on 2023-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_application_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
