# Generated by Django 4.1.5 on 2023-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_full_name_application_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
