# Generated by Django 4.1.5 on 2023-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_application_mobile_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
