# Generated by Django 4.1.5 on 2023-01-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_application_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
