# Generated by Django 4.1.5 on 2023-01-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
