# Generated by Django 4.1.5 on 2023-01-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
