# Generated by Django 4.1.5 on 2023-01-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
