# Generated by Django 4.1.5 on 2023-02-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_alter_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
