# Generated by Django 4.1.5 on 2023-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_job_company_address_job_company_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_size',
            new_name='department_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_place',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_zipcode',
        ),
    ]
