# Generated by Django 4.1.5 on 2023-02-28 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0028_alter_job_experience_alter_job_skillset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='department_name',
            field=models.CharField(choices=[('Computer Support Specialist', 'CSS'), ('Hardware Engineer', 'HWA'), ('Computer System Analyst', 'CSA'), ('Software Developer', 'SWD'), ('Programmer', 'PRG'), ('Web developer', 'WBD'), ('Network engineer', 'NWE'), ('Software Tester', 'SWT'), ('Frontend Developer', 'FD'), ('Backend Developer', 'BD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
