# Generated by Django 4.1.5 on 2023-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_application_user_alter_job_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department_name',
            field=models.CharField(choices=[('CSS', 'Computer Support Specialist'), ('HWA', 'Hardware Engineer'), ('CSA', 'Computer System Analyst '), ('SWD', 'Software Developer'), ('PRG', 'Programmer'), ('WBD', 'Web developer'), ('NWE', 'Network engineer'), ('SWT', 'Software Tester')], max_length=3),
        ),
    ]
