# Generated by Django 4.1.5 on 2023-03-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_alter_job_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
