# Generated by Django 4.1.5 on 2023-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_alter_job_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department_name',
            field=models.CharField(choices=[('Computer Support Specialist', 'CSS'), ('Hardware Engineer', 'HWA'), ('Computer System Analyst', 'CSA'), ('Software Developer', 'SWD'), ('Programmer', 'PRG'), ('Web developer', 'WBD'), ('Network engineer', 'NWE'), ('Software Tester', 'SWT'), ('Frontend Developer', 'FD'), ('Backend Developer', 'BD')], max_length=30),
        ),
    ]
