# Generated by Django 4.1.5 on 2023-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_alter_job_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
