# Generated by Django 4.1.5 on 2023-03-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_application_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
