# Generated by Django 4.1.7 on 2023-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('employed', 'Employed'), ('archived', 'Archived')], max_length=20),
        ),
    ]
