# Generated by Django 4.1.7 on 2023-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('employed', 'Employed'), ('active', 'Active'), ('archived', 'Archived')], max_length=20),
        ),
    ]
