# Generated by Django 4.1.7 on 2023-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department_name',
            field=models.CharField(choices=[('Computer Support Specialist', 'CSS'), ('Hardware Engineer', 'HARDWARE_ENGINEER'), ('Computer System Analyst', 'COMPUTER_SYSTEM_ANALYST'), ('Software Developer', 'SOFTWARE_DEVELOPER'), ('Programmer', 'PROGRAMMER'), ('Web Developer', 'WEB_DEVELOPER'), ('Network Engineer', 'NETWORK_ENGINEER'), ('Software Tester', 'SOFTWARE_TESTER'), ('Frontend Developer', 'FRONTEND_DEVELOPER'), ('Backend Developer', 'BACKEND_DEVELOPER')], max_length=30),
        ),
    ]
