# Generated by Django 4.1.7 on 2023-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_alter_job_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('employed', 'Employed'), ('active', 'Active'), ('archived', 'Archived')], default='Active', max_length=20),
        ),
    ]
