# Generated by Django 4.1.7 on 2023-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0045_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skillset_required',
            field=models.TextField(null=True),
        ),
    ]
