# Generated by Django 4.1.7 on 2023-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_alter_application_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('job.application',),
        ),
    ]
