# Generated by Django 4.2 on 2023-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_applicationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
