# Generated by Django 4.2 on 2023-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0049_alter_application_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
