# Generated by Django 4.2 on 2023-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0051_alter_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ("associate's degree", "Associate's Degree"), ("bachelor's degree", "Bachelor's Degree"), ("master's degree", "Master's Degree"), ('doctorate', 'Doctorate'), ('high_school', 'High School')], max_length=2553, null=True),
        ),
    ]
