# Generated by Django 4.2 on 2023-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0057_alter_application_level_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='level_education',
            field=models.CharField(choices=[('Certificate', 'CERTIFICATE'), ('Diploma', 'DIPLOMA'), ('Associate Degree', 'ASSOCIATE_DEGREE'), ('Bachelor Degree', 'BACHELOR_DEGREE'), ('Master Degree', 'MASTER_DEGREE'), ('Doctorate', 'DOCTORATE'), ('High School', ' HIGH_SCHOOL'), ('Professional Degree', 'PROFESSIONAL_DEGREE')], max_length=40),
        ),
    ]
